name: Bug Report 🪲
description: Report a bug to help us quickly identify and resolve issues.
title: '[Bug]: '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Please fill in the bug details in BDD style.

  - type: textarea
    id: given
    validations:
      required: true
    attributes:
      label: Given
      description: |
        Provide details about your setup, feature files, step definitions, and configuration. For example:
        ````
        I have the following setup:

        Feature file:
        ```gherkin
        # your feature here...
        ```

        Step definitions:
        ```javascript
        // your JavaScript code here...
        ```

        Playwright config:
        ```javascript
        // your Playwright config here...
        ```
        ````
      placeholder: What is your setup?

  - type: textarea
    id: when
    validations:
      required: true
    attributes:
      label: When
      description: |
        Describe the steps you performed to produce the issue. For example:
        ````
        I run the following command:
        ```shell
        npx bddgen && npx playwright test
        ```
        ````
      placeholder: What actions did you perform?

  - type: textarea
    id: then
    validations:
      required: true
    attributes:
      label: Then
      description: |
        Provide the **actual** outcome. For example:
        ````
        I see an error:
        ```
        Error: something went wrong...
        ```
        ````
      placeholder: What actually happened?

  - type: textarea
    id: expected-result
    validations:
      required: true
    attributes:
      label: Expected Result
      description: |
        Describe the **expected** result. For example:
        ````
        I expect no errors and all tests to pass.
        ````
      placeholder: What did you expect to happen?

  - type: input
    id: reproduction-url
    validations:
      required: false
    attributes:
      label: Reproduction Demo URL
      description: |
        You are **highly encouraged** to fork [playwright-bdd-example](https://github.com/vitalets/playwright-bdd-example) and modify it to reproduce the issue.
        Then push the changes and share the link below.
        It greatly speeds up issue resolution!
      placeholder: https://github.com/johndoe/playwright-bdd-example

  - type: textarea
    id: envinfo
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Please run `npx bddgen env` in the terminal and paste the output here.
      placeholder: |
        Playwright-bdd environment info:

        platform: darwin
        node: v20.11.1
        playwright-bdd: v8.1.0
        @playwright/test: v1.49.1
        @cucumber/cucumber: none
        Playwright config file: playwright.config.ts

      render: shell
