name: Bug Report 🪲
description: Create a bug report to help us improve
title: '[Bug]: '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Please fill in the bug details in BDD style.

  - type: textarea
    id: given
    validations:
      required: true
    attributes:
      label: Given
      description: |
        Describe your setup. For example:
        ````
        I have the following setup:

        Feature file:
        ```gherkin
        # your feature here...
        ```

        Step definitions:
        ```javascript
        // your JavaScript code here...
        ```

        Playwright config:
        ```javascript
        // your Playwright config here...
        ```
        ````
      placeholder: What is your setup?

  - type: textarea
    id: when
    validations:
      required: true
    attributes:
      label: When
      description: |
        Describe your actions. For example:
        ````
        I run the following command:
        ```shell
        npx bddgen && npx playwright test
        ```
        ````
      placeholder: What actions did you perform?

  - type: textarea
    id: then
    attributes:
      label: Then
      description: |
        Describe the **actual** result. For example:
        ````
        I see an error:
        ```
        Error: something went wrong...
        ```
        ````
      placeholder: What actually happened?

  - type: textarea
    id: expected-result
    validations:
      required: true
    attributes:
      label: But I expect
      description: |
        Describe the **expected** result. For example:
        ````
        I expect no errors and all tests to pass.
        ````
      placeholder: What did you expect?

  - type: input
    id: reproduction-url
    attributes:
      label: Reproduction demo URL
      description: |
        You are **highly encouraged** to try reproducing your bug on the [playwright-bdd-example](https://github.com/vitalets/playwright-bdd-example).
        It significantly reduces the time it takes to resolve your issue.
      placeholder: https://github.com/%your-name%/playwright-bdd-example

  - type: textarea
    id: envinfo
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Please run `npx bddgen env` in the terminal and paste the output here.
      placeholder: |
        Playwright-bdd environment info:

        platform: darwin
        node: v20.11.1
        playwright-bdd: v8.1.0
        @playwright/test: v1.49.1
        @cucumber/cucumber: none
        Playwright config file: playwright.config.ts
      render: shell
