name: Feature Request 🚀
description: Request a new feature or improvement
title: '[Feature]: '
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the following details to help us understand your request.

        **Note:** Providing as much detail as possible helps us prioritize and design the feature effectively.
  - type: textarea
    id: problem
    attributes:
      label: Describe the Problem
      description: Explain the current issue or limitation you’re facing. What challenge does this create?
      placeholder: Clearly describe the problem or limitation.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your idea for addressing the problem. How do you envision this feature working?
      placeholder: Detail the solution or feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Share any supporting information, such as screenshots, examples, or use cases.
      placeholder: Provide any additional context or background information.

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent or important is this feature for you?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
