name: Feature Request 🚀
description: Request a new feature or improvement
title: '[Feature]: '
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a new feature! 
        Please fill out the following details to help us understand your request.

        **Note**: Use backticks (\`\`\`) to format code blocks for better readability:
        ````
        My feature file:
        ```gherkin
        # your code in Gherkin...
        ```

        My step definitions:
        ```javascript
        // your code in JavaScript...
        ```
        ````
  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: Explain the current issue or limitation you’re facing.
      placeholder: What challenges do you have now?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your idea for addressing the problem.
      placeholder: How do you envision this feature working?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Share any supporting information, such as screenshots, examples, or use cases.
      placeholder: Any additional context that could be helpful?

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent is this feature for you?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
