name: Question ❓
description: Ask a question about Playwright-BDD usage
title: '[Question]: '
labels: question
body:
  - type: markdown
    attributes:
      value: |
        ## Need Help or Have a Question?  
        Feel free to ask your question below. Provide as many details as possible to help us give a clear and helpful answer.

        **Note**: Use backticks (\`\`\`) to format code blocks for better readability:
        ````
        My feature file:
        ```gherkin
        # your code in Gherkin...
        ```

        My step definitions:
        ```javascript
        // your code in JavaScript...
        ```
        ````
  - type: textarea
    id: question
    validations:
      required: true
    attributes:
      label: Question
      description: |
        Describe your question in detail.  
        Include any relevant context, code snippets, or links that might help clarify your question.
      placeholder: Provide as much detail as possible.
