# Update sponsors in README.md
name: update-sponsors
on:
  workflow_dispatch:
  schedule:
    # run daily at 00:00
    - cron: 0 0 * * *

permissions: write-all

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update sponsors in README.md
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          file: README.md

      - name: Push changes to main branch
        # See: https://github.com/JamesIves/github-pages-deploy-action/issues/1697
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: main
          folder: '.'
